apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-alert-frontend
  namespace: ${FOREX_ALERT_NAMESPACE}
  labels:
    app: forex-alert-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-alert-frontend
  template:
    metadata:
      labels:
        app: forex-alert-frontend
    spec:
      containers:
        - name: forex-alert-frontend
          image: asia.gcr.io/${FOREX_ALERT_GCP_PROJECT_ID}/forex-alert-frontend:${FOREX_ALERT_DOCKER_TAG}
          envFrom:
            - configMapRef:
                name: forex-alert-frontend-configmap
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: forex-alert-frontend-service
  namespace: ${FOREX_ALERT_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: forex-alert-frontend
  ports:
    - protocol: TCP
      port: 3000 # expose port
      targetPort: 3000
