kind: Namespace
apiVersion: v1
metadata:
  name: forex-alert
  labels:
    name: forex-alert

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-alert-redis
  namespace: forex-alert
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-alert-redis
  template:
    metadata:
      labels:
        app: forex-alert-redis
    spec:
      containers:
      - name: forex-alert-redis
        image: redis:latest
        ports:
        - containerPort: 6379
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: forex-alert-redis-service
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: forex-alert-redis

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forex-alert-backend-configmap
  namespace: forex-alert
data:
  NODE_ENV: production
  PRIVATE_KEY: 'n@e#w$f%a^r&m*m(e)m_o+r1i2z3e4567890'
  MONGO_URI: mongodb://lertumpai:sorawit5171718@34.87.156.163:27017/forex-alert
  COOKIE_SECURE: 'true'
  JOB_TIME: '2000'
  REDIS_HOST: forex-alert-redis-service
  REDIS_PORT: '6379'

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-alert-backend
  namespace: forex-alert
  labels:
    app: forex-alert-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-alert-backend
  template:
    metadata:
      labels:
        app: forex-alert-backend
    spec:
      containers:
        - name: forex-alert-backend
          image: asia.gcr.io/crested-lexicon-312308/forex-alert-backend:latest
          envFrom:
            - configMapRef:
                name: forex-alert-backend-configmap
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: forex-alert-backend-service
  namespace: forex-alert
spec:
  type: ClusterIP
  selector:
    app: forex-alert-backend
  ports:
    - protocol: TCP
      port: 5000 # expose port
      targetPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-alert-frontend
  namespace: forex-alert
  labels:
    app: forex-alert-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-alert-frontend
  template:
    metadata:
      labels:
        app: forex-alert-frontend
    spec:
      containers:
        - name: forex-alert-frontend
          image: asia.gcr.io/crested-lexicon-312308/forex-alert-frontend:latest
          envFrom:
            - configMapRef:
                name: forex-alert-frontend-configmap
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: forex-alert-frontend-service
  namespace: forex-alert
spec:
  type: ClusterIP
  selector:
    app: forex-alert-frontend
  ports:
    - protocol: TCP
      port: 3000 # expose port
      targetPort: 3000

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: forex-alert-frontend-configmap
  namespace: forex-alert
data:
  NODE_ENV: production
  SERVER_URL: https://forex-alert-nf.com

---
apiVersion: cert-manager.io/v1beta1
kind: ClusterIssuer
metadata:
  name: letencrypt-production
  namespace: forex-alert
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: slertumpai@gmail.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letencrypt-production
    # Enable the HTTP-01 challenge provider
    solvers:
      - http01:
          ingress:
            class: nginx

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    cert-manager.io/cluster-issuer: letencrypt-production
  name: nginx
  namespace: forex-alert
spec:
  tls:
    - hosts:
        - forex-alert.lertumpai.com
      secretName: forex-alert-tls-production
  rules:
    - host: forex-alert.lertumpai.com
      http:
        paths:
          - path: /backend/(.*)
            pathType: Prefix
            backend:
              service:
                name: forex-alert-backend-service
                port:
                  number: 5000
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: forex-alert-frontend-service
                port:
                  number: 3000
