apiVersion: apps/v1
kind: Deployment
metadata:
  name: forex-alert-cronjob
  namespace: ${FOREX_ALERT_NAMESPACE}
  labels:
    app: forex-alert-cronjob
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forex-alert-cronjob
  template:
    metadata:
      labels:
        app: forex-alert-cronjob
    spec:
      containers:
        - name: forex-alert-cronjob
          image: asia.gcr.io/${FOREX_ALERT_GCP_PROJECT_ID}/forex-alert-cronjob:${FOREX_ALERT_DOCKER_TAG}
          envFrom:
            - configMapRef:
                name: forex-alert-cronjob-configmap
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: forex-alert-cronjob-service
  namespace: ${FOREX_ALERT_NAMESPACE}
spec:
  type: ClusterIP
  selector:
    app: forex-alert-cronjob
  ports:
    - protocol: TCP
      port: 6000 # expose port
      targetPort: 6000
